Use 'C' locale when running tests
Otherwise the CalcModelTest fails with:
  CalcModelTest.changeTable:113 expected: <[1, 3.5, Column with 2 rows, 2.0, Test]> but was: <[1, Column with 2 rows, 2.0, Test, 3,5]>

(notice the difference: 3,5 instead of 3.5)